username: admin
password: password123
jwtSecret: 41a489117e6f39fbd6f8dbf6d2a0b41f6c6e584d1fa2481d33b2c967a7426893
aesKey: 38d381d2e4acb7c9ea7b1a5c7361afe4b0c30e9f50c6d8d2bcf26fef0b5ecb23
initDb: false
logLevel: dev
log:
    filename: ./log/app.log
    maxSize: 20
    maxBackups: 3
    maxAge: 7
    compress: true
database:
    path: ./data.db
    maxOpenConns: 10
    maxIdleConns: 5
    connMaxLifetime: 300
pipeline:
    batchSize: 1000
    channelSize: 10000
serverUrl: 0.0.0.0:8080
runWeb: false
webUrl: 0.0.0.0:8081
corsOrigins:
    - http://localhost:8081
